package: bower
user: javascript

platform:
  # - linux-32
  - linux-64
  - osx-64

install:
  - sudo yum erase -q gcc gcc-c++
  - sudo yum install -q gcc gcc-c++
  - conda config -f --add channels https://conda.binstar.org/wakari

engine:
  - python=2

script:
  - conda build .

build_targets: conda
